(function registerMobileTabletV2(global) {
  const { useEffect, useMemo, useRef, useState } = React;
  const {
    Activity, AlarmClock, ArrowDown, ArrowLeft, ArrowRightLeft, ArrowUp, Award,
    BarChart3, Bell, BookOpen, CalendarDays, Check, CheckCircle2, ChevronDown,
    ChevronLeft, ChevronRight, Circle, Clock3, CreditCard, Download, Droplet,
    Dumbbell, FileSpreadsheet, FileText, Flame, HeartPulse, Home, ListFilter,
    Medal, Menu, Mic, Moon, MoreHorizontal, Pause, Pill, Play, Plus, RefreshCcw,
    Search, Settings, Sparkles, Target, Timer, Tooth: ToothIcon, TrendingUp, Trophy, WalletCards,
    X
  } = global.lucideReact;
  const Tooth = ToothIcon || Sparkles;

  const isoDate = (date = new Date()) => {
    const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000);
    return local.toISOString().slice(0, 10);
  };
  const uid = (prefix) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  const money = (value, currency = 'COP') => new Intl.NumberFormat('es-CO', {
    style: 'currency', currency, maximumFractionDigits: currency === 'COP' ? 0 : 2
  }).format(Number(value || 0));
  const shortDate = (value) => {
    const date = new Date(`${value || isoDate()}T12:00:00`);
    return date.toLocaleDateString('es-CO', { day: 'numeric', month: 'short' });
  };
  const minutes = (value) => `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`;
  const initials = (name) => String(name || 'U').trim().slice(0, 1).toUpperCase();
  const allAgendaItems = (agenda) => Object.entries(agenda || {}).flatMap(([date, rows]) => (rows || []).map(row => ({ ...row, date: row.dueDate || date })));
  const activeHabits = (data) => (data.habits || []).filter(item => item.active !== false);
  const recordsFor = (data, habitId, date = isoDate()) => (data.records || []).some(record => record.habitId === habitId && record.date === date && record.completed);
  const routeParam = (name, fallback) => new URLSearchParams(location.search).get(name) || fallback;
  const useMobileV2Viewport = () => {
    const read = () => global.matchMedia('(max-width: 1180px)').matches;
    const [isMobileTablet, setMobileTablet] = useState(read);
    useEffect(() => {
      const media = global.matchMedia('(max-width: 1180px)');
      const update = () => setMobileTablet(media.matches);
      media.addEventListener?.('change', update);
      return () => media.removeEventListener?.('change', update);
    }, []);
    return { isMobileTablet, isPhone: global.matchMedia('(max-width: 767px)').matches };
  };

  const IconCircle = ({ children, tone = 'red', className = '' }) => <span className={`m2-icon m2-icon-${tone} ${className}`}>{children}</span>;
  const Card = ({ children, className = '', as: Tag = 'section', ...props }) => <Tag className={`m2-card ${className}`.trim()} {...props}>{children}</Tag>;
  const PageTitle = ({ title, subtitle, action }) => <div className="m2-title-row"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>;
  const Tabs = ({ items, value, onChange, label }) => <div className="m2-tabs" role="tablist" aria-label={label}>{items.map(item => <button type="button" role="tab" aria-selected={value === item.id} className={value === item.id ? 'is-active' : ''} key={item.id} onClick={() => onChange(item.id)}>{item.icon && <item.icon size={19} />}{item.label}</button>)}</div>;
  const Button = ({ children, secondary = false, className = '', ...props }) => <button type="button" className={`m2-button ${secondary ? 'is-secondary' : ''} ${className}`.trim()} {...props}>{children}</button>;
  const Empty = ({ icon: Icon = Sparkles, title, text, action, actionLabel }) => <Card className="m2-empty"><IconCircle><Icon size={24} /></IconCircle><h3>{title}</h3><p>{text}</p>{action && <Button onClick={action}>{actionLabel}</Button>}</Card>;

  const MobileV2Header = ({ userName, dateLabel, streak, onNotifications }) => (
    <header className="m2-header" data-testid="mobile-v2-header">
      <div className="m2-brand"><span className="m2-logo" aria-hidden="true"><i/><i/><i/><i/></span><strong>HabitFlow</strong></div>
      <div className="m2-date"><CalendarDays size={18} /><span>{dateLabel}</span></div>
      <div className="m2-header-actions">
        <span className="m2-streak"><Flame size={22} /><b>{streak}</b></span>
        <button type="button" aria-label="Notificaciones" onClick={onNotifications}><Bell size={22} /><i /></button>
        <span className="m2-avatar">{initials(userName)}</span>
      </div>
    </header>
  );

  const PRIMARY_NAV = [
    { id: 'dashboard', label: 'Inicio', icon: Home },
    { id: 'habits', label: 'Hábitos', icon: Target },
    { id: 'agenda', label: 'Agenda', icon: CalendarDays },
    { id: 'finance', label: 'Finanzas', icon: WalletCards }
  ];
  const MORE_NAV = [
    { id: 'workout', label: 'Entreno', icon: Dumbbell },
    { id: 'pomodoro', label: 'Pomodoro', icon: Timer },
    { id: 'dreams', label: 'Metas', icon: Sparkles },
    { id: 'health', label: 'Salud', icon: HeartPulse },
    { id: 'settings', label: 'Configuración', icon: Settings },
    { id: 'creator', label: 'Creador', icon: Award }
  ];

  const MobileV2MoreSheet = ({ open, view, onClose, onNavigate, creatorAccess }) => {
    if (!open) return null;
    const items = creatorAccess ? MORE_NAV : MORE_NAV.filter(item => item.id !== 'creator');
    return <><button className="m2-scrim" onClick={onClose} aria-label="Cerrar menú" /><section className="m2-more-sheet" role="dialog" aria-modal="true" data-testid="mobile-v2-more-sheet"><i className="m2-sheet-handle" /><header><div><span>HabitFlow</span><h2>Más secciones</h2></div><button onClick={onClose} aria-label="Cerrar"><X size={22} /></button></header><div className="m2-more-grid">{items.map(item => <button key={item.id} className={view === item.id ? 'is-active' : ''} onClick={() => { onNavigate(item.id); onClose(); }}><item.icon size={25} /><span>{item.label}</span></button>)}</div></section></>;
  };

  const MobileV2BottomNav = ({ view, onNavigate, moreOpen, onToggleMore, workoutActive = false }) => {
    const moreActive = MORE_NAV.some(item => item.id === view);
    const items = workoutActive ? [PRIMARY_NAV[0], PRIMARY_NAV[1], { id: 'workout', label: 'Entreno', icon: Dumbbell }, PRIMARY_NAV[3]] : PRIMARY_NAV;
    return <nav className="m2-bottom-nav" aria-label="Navegación principal" data-testid="mobile-v2-bottom-nav">{items.map(item => <button type="button" key={item.id} className={view === item.id ? 'is-active' : ''} onClick={() => onNavigate(item.id)}><item.icon size={24} /><span>{item.label}</span></button>)}<button type="button" className={moreOpen || moreActive ? 'is-active' : ''} onClick={onToggleMore}><MoreHorizontal size={25} /><span>Más</span></button></nav>;
  };

  const ProgressRing = ({ value = 0, label = 'Completado hoy', size = 104 }) => <div className="m2-ring" style={{ '--m2-progress': `${Math.max(0, Math.min(100, value))}%`, width: size, height: size }}><strong>{Math.round(value)}%</strong><span>{label}</span></div>;

  const HomePage = ({ data, navigate, quickAction, streak }) => {
    const habits = activeHabits(data);
    const today = isoDate();
    const done = habits.filter(habit => recordsFor(data, habit.id, today)).length;
    const pct = habits.length ? Math.round(done / habits.length * 100) : 0;
    const agenda = (data.agenda?.[today] || []).slice(0, 3);
    const pending = habits.filter(habit => !recordsFor(data, habit.id, today)).slice(0, 3);
    const finance = data.financeData || {};
    const expenses = (finance.transactions || []).filter(item => item.type === 'expense').reduce((sum, item) => sum + Number(item.amount || 0), 0);
    return <div className="m2-page m2-home-page"><div className="m2-hero-row"><div><h1>Buenas tardes, <em>{data.user?.name || 'Usuario'}.</em></h1><p>Mantén el enfoque. Pequeñas acciones, grandes resultados.</p></div><ProgressRing value={pct} /></div>
      <button className="m2-capture" onClick={() => quickAction('newTask')}><Sparkles size={22} /><span>Captura algo rápido... tarea, hábito, gasto o evento</span><Mic size={23} /></button>
      <div className="m2-quick-grid">{[
        ['newTask', 'Nueva tarea', CalendarDays], ['startPomodoro', 'Pomodoro', Timer], ['newHabit', 'Nuevo hábito', Target], ['newExpense', 'Nuevo gasto', WalletCards]
      ].map(([id, label, Icon]) => <button key={id} onClick={() => quickAction(id)}><Icon size={29} /><span>{label}</span></button>)}</div>
      <div className="m2-home-grid">
        <Card className="m2-list-card"><header><h2><CalendarDays size={20} />Plan del día</h2><button onClick={() => navigate('agenda')}>Ver todo</button></header>{agenda.length ? agenda.map(item => <div className="m2-line" key={item.id}><Circle size={19} /><span>{item.text || item.title}</span><small>{item.startTime || item.dueTime || 'Hoy'}</small></div>) : <p className="m2-muted">Tu plan está despejado. Añade una tarea.</p>}<button className="m2-link" onClick={() => quickAction('newTask')}><Plus size={16} />Añadir tarea</button></Card>
        <Card className="m2-list-card"><header><h2><RefreshCcw size={20} />Hábitos pendientes</h2><button onClick={() => navigate('habits')}>Ver todo</button></header>{pending.length ? pending.map((habit, index) => <div className="m2-line" key={habit.id}><IconCircle tone={['green','amber','blue'][index] || 'red'}><Target size={18} /></IconCircle><span>{habit.name}</span><small>0/1</small></div>) : <p className="m2-muted">Todos los hábitos están listos.</p>}<button className="m2-link" onClick={() => quickAction('newHabit')}><Plus size={16} />Añadir hábito</button></Card>
        <Card className="m2-pomodoro-mini"><header><h2><Timer size={20} />Pomodoro rápido</h2><Settings size={18} /></header><strong>25:00</strong><div className="m2-duration-row"><button className="is-active">25 min</button><button>15 min</button><button>50 min</button></div><Button onClick={() => navigate('pomodoro')}><Play size={18} />Iniciar</Button></Card>
        <Card className="m2-finance-mini"><header><h2><WalletCards size={20} />Finanzas rápidas</h2><button onClick={() => navigate('finance')}>Ver todo</button></header><span>Gasto registrado</span><strong>{money(expenses, finance.currency || 'USD')}</strong><div className="m2-sparkline"><i/><i/><i/><i/><i/></div><hr/><span>Presupuesto mensual</span><b>{money(finance.monthlyBudget || 0, finance.currency || 'USD')}</b><div className="m2-progress"><i style={{width:'35%'}}/></div></Card>
        <Card className="m2-xp-card"><header><span>Nivel {data.user?.level || 1}</span><small>{data.user?.xp || 0} XP</small></header><div><Medal size={48}/><span><strong>Camino imparable</strong><small>{data.user?.xp || 0} XP acumulados</small><i className="m2-progress"><b style={{width:'57%'}}/></i></span></div></Card>
        <Card className="m2-achievement"><header><h2>Logros recientes</h2><button>Ver todos</button></header><div><Trophy size={44}/><span><strong>Racha de fuego</strong><small>{streak} días consecutivos</small></span></div></Card>
      </div>
    </div>;
  };

  const HabitsPage = ({ data, onCompleteHabit, hydration, onToggleHydrationWidget, quickAction }) => {
    const [period, setPeriod] = useState('week');
    const habits = activeHabits(data).slice(0, 4);
    const days = Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (6 - index)); return { date: isoDate(date), label: ['D','L','M','M','J','V','S'][date.getDay()] }; });
    const completed = habits.reduce((sum, habit) => sum + days.filter(day => recordsFor(data, habit.id, day.date)).length, 0);
    const pct = habits.length ? Math.round(completed / (habits.length * 7) * 100) : 0;
    return <div className="m2-page"><PageTitle title="Mis hábitos" subtitle="Pequeños hábitos, grandes cambios." action={<div className="m2-title-actions"><Tabs value={period} onChange={setPeriod} items={[{id:'week',label:'Semanal'},{id:'month',label:'Mensual'}]} /><Button onClick={() => quickAction('newHabit')}><Plus/>Nuevo hábito</Button></div>} />
      <div className="m2-metrics-3"><Card><IconCircle><Activity/></IconCircle><strong>{habits.length}</strong><span>Hábitos activos</span></Card><Card><ProgressRing value={pct} size={82}/><span>Cumplimiento<br/>semanal</span></Card><Card><IconCircle><Flame/></IconCircle><strong>{Math.max(0, ...habits.map(h => Number(h.streak || 0)))}</strong><span>Racha global<br/>días</span></Card></div>
      <Card className="m2-habit-table"><header><h2>Vista semanal</h2><span>{shortDate(days[0].date)} – {shortDate(days[6].date)}</span><div><button><ChevronLeft/></button><button><ChevronRight/></button></div></header><div className="m2-habit-head"><span/><span>{days.map(day => <b key={day.date}>{day.label}</b>)}</span></div>{habits.length ? habits.map((habit,index) => <div className="m2-habit-row" key={habit.id}><div><IconCircle tone={['blue','amber','green','purple'][index]}>{index===0?<Droplet/>:index===1?<BookOpen/>:index===2?<Activity/>:<Sparkles/>}</IconCircle><span>{habit.name}</span></div><div>{days.map(day => {const done=recordsFor(data,habit.id,day.date);return <button key={day.date} className={done?'is-done':''} onClick={() => onCompleteHabit(habit.id,day.date)}>{done?<Check/>:<Circle/>}</button>})}</div></div>) : <Empty title="Aún no tienes hábitos" text="Crea tu primer hábito para construir constancia." action={() => quickAction('newHabit')} actionLabel="Nuevo hábito"/>}<footer>{habits.map((habit,index)=><span key={habit.id}><i className={`tone-${['blue','amber','green','purple'][index]}`}/>{habit.name}</span>)}</footer></Card>
      <Card className="m2-widget-toggle"><IconCircle><Droplet/></IconCircle><div><h3>Widget de hidratación</h3><p>Muestra tu progreso de hidratación en la barra lateral / utilidades de la app.</p></div><button className={hydration.widgetEnabled?'is-on':''} onClick={() => onToggleHydrationWidget(!hydration.widgetEnabled)}><i/></button></Card>
    </div>;
  };

  const PomodoroPage = ({ data, onUpdatePomodoro }) => {
    const [mode,setMode]=useState('focus'); const [duration,setDuration]=useState(25); const [seconds,setSeconds]=useState(25*60); const [running,setRunning]=useState(false); const [notes,setNotes]=useState(''); const [sound,setSound]=useState(true);
    useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(current=>{if(current>1)return current-1;setRunning(false);onUpdatePomodoro(prev=>[...(prev||[]),{id:uid('pomodoro'),date:isoDate(),minutes:duration,mode}]);return duration*60}),1000);return()=>clearInterval(id)},[running,duration,mode,onUpdatePomodoro]);
    const selectDuration=(value)=>{setDuration(value);setSeconds(value*60);setRunning(false)};
    return <div className="m2-page m2-pomodoro-page"><Card className="m2-pomo-main"><Tabs value={mode} onChange={setMode} items={[{id:'focus',label:'Enfoque',icon:Target},{id:'break',label:'Descanso',icon:Clock3},{id:'long',label:'Largo',icon:Moon}]} /><div className="m2-timer-ring"><span>{mode==='focus'?'Enfoque':mode==='break'?'Descanso':'Descanso largo'}</span><strong>{minutes(seconds)}</strong><small>Quédate enfocado</small></div><div className="m2-timer-controls"><button onClick={()=>setRunning(false)}><Pause/></button><button className="is-primary" onClick={()=>setRunning(v=>!v)}>{running?<Pause/>:<Play/>}</button><button onClick={()=>setSeconds(duration*60)}><RefreshCcw/></button></div><div className="m2-duration-row">{[25,15,50].map(value=><button className={duration===value?'is-active':''} onClick={()=>selectDuration(value)} key={value}>{value} min</button>)}</div><Card className="m2-pomo-settings"><div><Bell/><span><small>Sonido</small>Campana suave</span><ChevronRight/></div><div><Target/><span><small>Modo de enfoque</small>Sin distracciones</span><ChevronRight/></div></Card></Card>
      <Card className="m2-toggle-line"><IconCircle><Bell/></IconCircle><div><h3>Alerta sonora al finalizar</h3><p>También avisar al iniciar descansos</p></div><button className={sound?'is-on':''} onClick={()=>setSound(v=>!v)}><i/></button></Card><Card className="m2-alert-line"><IconCircle><Bell/></IconCircle><span>Cuando finalice el tiempo, verás una alerta en pantalla completa.</span><X/></Card>
      <div className="m2-pomo-bottom"><Card><header><h2><FileText/>Notas del pomodoro</h2><MoreHorizontal/></header><textarea value={notes} onChange={event=>setNotes(event.target.value)} maxLength={300} placeholder="Escribe tus notas aquí..."/><small>{notes.length} / 300</small></Card><Card><header><h2><CheckCircle2/>Pendientes del pomodoro</h2><b>4</b><MoreHorizontal/></header>{['Revisar propuesta del proyecto','Preparar presentación Q2','Responder correos importantes','Actualizar reporte de ventas'].map(item=><label key={item}><input type="checkbox"/>{item}</label>)}<button><Plus/>Añadir tarea rápida...</button></Card></div>
    </div>;
  };

  const agendaTone = (index) => ['green','blue','red','purple','amber'][index%5];
  const AgendaItem = ({ item,index }) => <Card className={`m2-agenda-item tone-${agendaTone(index)}`}><IconCircle tone={agendaTone(index)}>{index%5===0?<Activity/>:index%5===1?<BookOpen/>:index%5===2?<Target/>:index%5===3?<Sparkles/>:<Clock3/>}</IconCircle><div><strong>{item.text||item.title||'Evento'}</strong><span>{item.category||'Personal'} · {item.startTime||item.dueTime||'Todo el día'}{item.endTime?` – ${item.endTime}`:''}</span></div><ChevronRight/></Card>;

  const AgendaPage = ({ data, onUpdateAgenda }) => {
    const initial = routeParam('agenda','week'); const [section,setSection]=useState(['week','month','list','upcoming'].includes(initial)?initial:'week'); const [filters,setFilters]=useState(false);
    const items=allAgendaItems(data.agenda).sort((a,b)=>`${a.date}${a.startTime||''}`.localeCompare(`${b.date}${b.startTime||''}`)); const today=isoDate(); const upcoming=items.filter(item=>item.date>=today).slice(0,8);
    const change=(id)=>{setSection(id);const u=new URL(location.href);u.searchParams.set('agenda',id);history.replaceState({},'',u)};
    const createQuick=()=>{const text=global.prompt('Nombre del evento');if(!text)return;onUpdateAgenda(today,prev=>[...prev,{id:uid('task'),text,completed:false,dueDate:today,startTime:'09:00',category:'Personal'}])};
    const tabs=[{id:'day',label:'Día'},{id:'week',label:'Semana'},{id:'month',label:'Mes'},{id:'list',label:'Agenda'}];
    if(section==='upcoming')return <div className="m2-page"><PageTitle title="Próximos eventos" subtitle="Todo lo que viene en los próximos días."/><Tabs value="seven" onChange={()=>{}} items={[{id:'today',label:'Hoy'},{id:'tomorrow',label:'Mañana'},{id:'seven',label:'7 días'},{id:'month',label:'Mes'}]}/><Card className="m2-upcoming-summary"><IconCircle><CalendarDays/></IconCircle><strong>{upcoming.length}</strong><span>eventos próximos<br/><small>En los próximos 7 días</small></span><hr/><IconCircle><Target/></IconCircle><strong>{Math.min(3,upcoming.length)}</strong><span>prioridades<br/><small>Eventos clave</small></span></Card><div className="m2-agenda-list">{upcoming.map((item,index)=><AgendaItem key={item.id||index} item={item} index={index}/>)}</div></div>;
    return <div className="m2-page"><PageTitle title="Agenda" subtitle={section==='month'?'Organiza tu mes y mantén el enfoque.':section==='list'?'Todo tu calendario en una lista clara.':'Organiza tu semana y mantén el enfoque.'}/><Tabs value={section==='list'?'list':section} onChange={id=>change(id==='day'?'week':id)} items={tabs}/><div className="m2-agenda-toolbar"><button><ChevronLeft/></button><strong><CalendarDays/> {section==='month'?'Julio 2026':section==='list'?'Todos los eventos':'13 jul – 19 jul 2026'}</strong><button><ChevronRight/></button>{section==='list'&&<Button onClick={createQuick}><Plus/>Nueva tarea</Button>}<button className="m2-filter" onClick={()=>setFilters(true)}><ListFilter/>Filtros</button></div>
      {section==='week'&&<><Card className="m2-week-days">{['L 13','M 14','M 15','J 16','V 17','S 18','D 19'].map((day,index)=><span className={index===1?'is-today':''} key={day}>{day.split(' ')[0]}<b>{day.split(' ')[1]}</b><i/></span>)}</Card><Card className="m2-week-grid"><div className="m2-hours">{['07','09','11','13','15','17','19','21'].map(h=><span key={h}>{h}:00</span>)}</div>{Array.from({length:7},(_,day)=><div className="m2-day-column" key={day}>{upcoming.slice(0,day%3+2).map((item,index)=><span key={item.id||index} className={`tone-${agendaTone(index+day)}`} style={{top:`${index*92+10}px`}}>{item.text||item.title||'Evento'}<small>{item.startTime||'09:00'}</small></span>)}</div>)}</Card><Card className="m2-week-summary"><div><h3><BarChart3/>Resumen semanal</h3><ProgressRing value={84} size={92}/><strong>84% completado</strong></div><div><h3>Próximos eventos</h3>{upcoming.slice(0,2).map((item,index)=><span key={item.id||index}>{item.text||item.title||'Evento'}<small>{item.startTime||'Hoy'}</small></span>)}</div></Card></>}
      {section==='month'&&<><Card className="m2-month-grid">{['L','M','M','J','V','S','D'].map((d,i)=><b key={`${d}${i}`}>{d}</b>)}{Array.from({length:35},(_,i)=><button key={i} className={i===15?'is-today':''}>{i<3?29+i:i-2}<span>{i%2===0&&<i/>}{i%5===0&&<i/>}</span></button>)}</Card><h2 className="m2-section-title">Resumen del mes</h2><div className="m2-metrics-3"><Card><CalendarDays/><strong>{items.length}</strong><span>Eventos</span></Card><Card><Target/><strong>{items.filter(i=>i.completed).length}</strong><span>Completados</span></Card><Card><Clock3/><strong>{items.length*2} h</strong><span>Planificado</span></Card></div><h2 className="m2-section-title">Próximos eventos</h2><div className="m2-agenda-list">{upcoming.slice(0,3).map((item,index)=><AgendaItem key={item.id||index} item={item} index={index}/>)}</div></>}
      {section==='list'&&<><div className="m2-chip-row"><button className="is-active">Todos</button><button>Trabajo</button><button>Personal</button><button>Hábitos</button></div><div className="m2-agenda-list"><h2>Hoy <small>· {shortDate(today)}</small></h2>{(upcoming.length?upcoming:items).map((item,index)=><AgendaItem key={item.id||index} item={item} index={index}/>)}</div><Button secondary onClick={()=>change('upcoming')}>Ver próximos eventos</Button></>}
      {filters&&<><button className="m2-scrim" onClick={()=>setFilters(false)}/><section className="m2-filter-sheet"><i className="m2-sheet-handle"/><header><h2>Filtros</h2><button onClick={()=>setFilters(false)}><X/></button></header>{[['Calendarios',['Personal','Trabajo','Salud','Finanzas','Estudios']],['Tipo',['Tarea','Evento','Hábito','Reunión']],['Fecha',['Hoy','Esta semana','Este mes']],['Estado',['Pendiente','Completado']],['Hora',['Mañana','Tarde','Noche']]].map(([title,options])=><div key={title}><h3>{title}</h3><div className="m2-chip-row">{options.map((option,index)=><button className={index===0?'is-active':''} key={option}>{option}</button>)}</div></div>)}<footer><Button secondary onClick={()=>setFilters(false)}>Limpiar</Button><Button onClick={()=>setFilters(false)}>Aplicar filtros</Button></footer></section></>}
    </div>;
  };

  const WorkoutTabs = ({ value, onChange }) => <Tabs label="Secciones de Entreno" value={value} onChange={onChange} items={[{id:'summary',label:'Hoy',icon:CalendarDays},{id:'routines',label:'Rutinas',icon:Dumbbell},{id:'library',label:'Biblioteca',icon:BookOpen},{id:'progress',label:'Progreso',icon:TrendingUp}]}/>;
  const WorkoutPage = ({ data, onUpdateWorkout }) => {
    const initial=routeParam('workout','summary');const [section,setSection]=useState(initial);const [catalog,setCatalog]=useState([]);const workout=data.workoutData||{};
    useEffect(()=>{if(['summary','library','active'].includes(section))global.HabitFlowExerciseDataset?.loadCatalog().then(items=>setCatalog(items.slice(0,18))).catch(()=>{})},[section]);
    const change=id=>{setSection(id);const u=new URL(location.href);id==='summary'?u.searchParams.delete('workout'):u.searchParams.set('workout',id);history.replaceState({},'',u)};
    const start=(routine)=>{const chosen=(routine?.exercises||[]).map((row,index)=>{const ex=catalog.find(item=>String(item.id)===String(row.exerciseId||row.id))||catalog[index]||{};return {exerciseId:ex.id,exerciseName:ex.name||row.name||'Ejercicio',gifUrl:ex.gif_url||'',category:ex.category||'',sets:Array.from({length:Number(row.sets||3)},(_,i)=>({id:uid('set'),setNumber:i+1,reps:Number(String(row.reps||10).match(/\d+/)?.[0]||10),weight:Number(row.weight||0),completed:false}))}});if(!chosen.length&&catalog[0])chosen.push({exerciseId:catalog[0].id,exerciseName:catalog[0].name,gifUrl:catalog[0].gif_url,category:catalog[0].category,sets:Array.from({length:4},(_,i)=>({id:uid('set'),setNumber:i+1,reps:10,weight:0,completed:false}))});const session={id:uid('session'),routineName:routine?.name||'Entreno libre',startedAt:new Date().toISOString(),status:'active',currentExerciseIndex:0,exercises:chosen};onUpdateWorkout(prev=>({...prev,activeSession:session,updatedAt:new Date().toISOString()}));change('active')};
    const media=item=>global.HabitFlowExerciseDataset?.resolveExerciseMedia(item?.image||item?.gif_url||item?.gifUrl)||'';
    if(section==='active'){const session=workout.activeSession; if(!session)return <div className="m2-page"><PageTitle title="Sesión activa" subtitle="Tu entrenamiento se guardará automáticamente."/><Empty icon={Dumbbell} title="No hay una sesión activa" text="Inicia una rutina para registrar tus series." action={()=>change('routines')} actionLabel="Ver rutinas"/></div>;const ex=session.exercises?.[session.currentExerciseIndex||0];return <div className="m2-page"><PageTitle title="Sesión activa" subtitle={session.routineName||'Entreno libre'} action={<Card className="m2-session-time"><Dumbbell/>Sesión en progreso<strong>00:42:17</strong></Card>}/><Card className="m2-current-exercise"><div className="m2-workout-media">{media(ex)&&<img src={media(ex)} alt="" loading="lazy"/>}</div><div><span>Ejercicio actual</span><h2>{ex?.exerciseName||'Ejercicio'}</h2><em>{ex?.category||'Entreno'}</em><b><Timer/>Descanso 01:12</b></div></Card><Card className="m2-sets"><header><span>Set</span><span>Peso (kg)</span><span>Reps</span><Check/></header>{(ex?.sets||[]).map((set,index)=><div key={set.id}><strong>{index+1}</strong><span><button>−</button>{set.weight||'—'}<button>+</button></span><span><button>−</button>{set.reps||'—'}<button>+</button></span><button className={set.completed?'is-done':''} onClick={()=>onUpdateWorkout(prev=>({...prev,activeSession:{...prev.activeSession,exercises:prev.activeSession.exercises.map((item,i)=>i?(item):({...item,sets:item.sets.map((s,j)=>j===index?{...s,completed:!s.completed}:s)}))}}))}>{set.completed?<Check/>:<Circle/>}</button></div>)}<Button><Dumbbell/>Completar set</Button></Card><h2 className="m2-section-title">Siguientes ejercicios</h2><div className="m2-exercise-list">{session.exercises?.slice(1,4).map((item,index)=><Card key={item.exerciseId||index}>{media(item)&&<img src={media(item)} alt="" loading="lazy"/>}<b>{index+1}</b><span><strong>{item.exerciseName}</strong><small>{item.category}</small></span><ChevronRight/></Card>)}</div><div className="m2-two-actions"><Button secondary>Terminar ejercicio</Button><Button secondary onClick={()=>onUpdateWorkout(prev=>({...prev,activeSession:null}))}>Finalizar sesión</Button></div></div>}
    const routines=workout.routines||[];
    return <div className="m2-page"><PageTitle title="Entreno" subtitle={section==='routines'?'Tus rutinas listas para avanzar.':section==='library'?'Explora ejercicios y encuentra el indicado.':section==='progress'?'Tu evolución, clara y accionable.':'Tu sesión, más clara y potente.'}/><WorkoutTabs value={section} onChange={change}/>
      {section==='summary'&&<><Card className="m2-workout-hero"><div><span><Dumbbell/>Entreno de hoy</span><h2>{routines[0]?.name||'Entreno libre'}</h2><p>{routines[0]?.exercises?.length||0} ejercicios · 60 min</p><Button onClick={()=>start(routines[0])}><Play/>Iniciar sesión</Button></div></Card><div className="m2-chip-row"><button className="is-active">Todos</button><button>Pecho</button><button>Espalda</button><button>Piernas</button><button>Hombros</button></div><Card className="m2-active-routine"><IconCircle><Dumbbell/></IconCircle><div><small>Rutina activa</small><strong>{routines[0]?.name||'Entreno libre'}</strong><span>{routines[0]?.exercises?.length||0} ejercicios · 60 min</span></div><Button secondary onClick={()=>change('routines')}>Editar rutina</Button></Card><h2 className="m2-section-title">Biblioteca de ejercicios</h2><div className="m2-exercise-list">{catalog.slice(0,4).map(item=><Card key={item.id}>{media(item)&&<img src={media(item)} alt="" loading="lazy"/>}<span><strong>{item.name}</strong><small>{item.category||item.body_part} · {item.equipment}</small></span><ChevronRight/></Card>)}</div></>}
      {section==='routines'&&<><Card className="m2-routines-head"><IconCircle><Dumbbell/></IconCircle><div><h2>Mis rutinas</h2><span>{routines.length} activas</span></div><Button onClick={()=>global.alert('El constructor de rutinas conserva la lógica desktop y se conectará en la siguiente vista.') }><Plus/>Nueva rutina</Button></Card>{routines.length?<div className="m2-routine-list">{routines.map((routine,index)=><Card key={routine.id}><div className={`m2-routine-photo tone-${agendaTone(index)}`}/><div><h2><Dumbbell/>{routine.name}</h2><p>{routine.exercises?.length||0} ejercicios · 60 min · Intermedio</p><div className="m2-chip-row"><span>Pecho</span><span>Hombros</span><span>Tríceps</span></div><div className="m2-two-actions"><Button onClick={()=>start(routine)}><Play/>Iniciar</Button><Button secondary>Editar</Button></div></div></Card>)}</div>:<Empty icon={Dumbbell} title="No hay rutinas guardadas" text="Crea un plan con ejercicios reales del catálogo." action={()=>change('library')} actionLabel="Explorar ejercicios"/>}</>}
      {section==='library'&&<><div className="m2-search"><Search/><input placeholder="Buscar ejercicio, músculo o equipo"/></div><div className="m2-chip-row"><button className="is-active">Todos</button><button>Pecho</button><button>Espalda</button><button>Piernas</button><button>Hombros</button></div><div className="m2-library-list">{catalog.slice(0,8).map(item=><Card key={item.id}>{media(item)&&<img src={media(item)} alt="" loading="lazy"/>}<div><h2>{item.name}</h2><span><Target/>{item.category||item.body_part}</span><span><Dumbbell/>{item.equipment}</span><small>Intermedio</small></div><ChevronRight/></Card>)}</div></>}
      {section==='progress'&&<><Card className="m2-period"><CalendarDays/>Esta semana<ChevronDown/></Card><div className="m2-workout-kpis"><Card><IconCircle><CalendarDays/></IconCircle><span>Sesiones completadas<strong>{workout.sessions?.length||0}/5</strong></span><i className="m2-progress"><b style={{width:`${Math.min(100,(workout.sessions?.length||0)*20)}%`}}/></i></Card><Card><IconCircle><Dumbbell/></IconCircle><span>Volumen total<strong>{Math.round((workout.sessions||[]).reduce((s,x)=>s+Number(x.totalVolume||0),0))} kg</strong></span><TrendingUp/></Card></div><div className="m2-progress-grid"><Card className="m2-chart"><h2>Volumen semanal</h2><div className="m2-line-chart">{[35,55,30,72,54,45,28].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div></Card><Card className="m2-compliance"><h2>Cumplimiento</h2><ProgressRing value={60} size={150}/><strong>3 de 5 sesiones</strong></Card></div><div className="m2-metrics-2"><Card><IconCircle><Flame/></IconCircle><span>Racha actual<strong>4 sesiones</strong></span></Card><Card><IconCircle><Activity/></IconCircle><span>Músculo más trabajado<strong>Pecho</strong></span></Card></div></>}
    </div>;
  };

  const GoalsPage = ({ data, onUpdateDreamGoals }) => {
    const [section,setSection]=useState(()=>{const requested=routeParam('goals','active');return ['active','completed','dreams'].includes(requested)?requested:'active'});const goals=data.dreamGoals||[];const visible=section==='completed'?goals.filter(g=>Number(g.current)>=Number(g.target)):section==='active'?goals.filter(g=>Number(g.current)<Number(g.target)):goals;
    const contribute=goal=>{const raw=global.prompt('¿Cuánto quieres aportar?');const amount=Number(raw||0);if(amount<=0)return;onUpdateDreamGoals(prev=>(prev||[]).map(item=>item.id===goal.id?{...item,current:Math.min(Number(item.target||0),Number(item.current||0)+amount)}:item))};
    return <div className="m2-page"><PageTitle title="Metas" subtitle="Ahorra hoy para construir el mañana que sueñas."/><Tabs value={section} onChange={setSection} items={[{id:'active',label:'Activas'},{id:'completed',label:'Completadas'},{id:'dreams',label:'Sueños'}]}/>{section==='dreams'&&<Card className="m2-dream-intro"><IconCircle><Sparkles/></IconCircle><div><h2>Tus sueños, tu futuro.</h2><p>Convierte tus sueños en metas y hazlos realidad paso a paso.</p></div><span><small>Sueños guardados</small><strong>{goals.length}</strong><small>Valor total estimado</small><b>{money(goals.reduce((s,g)=>s+Number(g.target||0),0),'USD')}</b></span></Card>}<div className={`m2-goal-list ${section==='dreams'?'is-dreams':''}`}>{visible.length?visible.map((goal,index)=>{const pct=goal.target?Math.min(100,Math.round(Number(goal.current||0)/Number(goal.target)*100)):0;return <Card key={goal.id} className={index===0&&section==='active'?'is-featured':''}>{goal.image&&<img src={goal.image} alt=""/>}<div><h2>{goal.icon} {goal.title}</h2>{section==='completed'&&<em><CheckCircle2/>Completada</em>}<span>Meta<strong>{money(goal.target,'USD')}</strong></span>{section!=='dreams'&&<span>Ahorrado<strong className={section==='completed'?'is-green':''}>{money(goal.current,'USD')}</strong></span>}<i className="m2-progress"><b style={{width:`${pct}%`}}/></i><b className="m2-goal-pct">{pct}%</b>{section==='dreams'?<Button onClick={()=>setSection('active')}>Convertir en meta</Button>:section==='active'&&<Button onClick={()=>contribute(goal)}>Aportar</Button>}</div></Card>}):<Empty title="No hay metas en esta sección" text="Tus metas aparecerán aquí cuando coincidan con este estado."/>}</div></div>;
  };

  const walletTabs=[{id:'summary',label:'Resumen',icon:BarChart3},{id:'accounts',label:'Cuentas',icon:CreditCard},{id:'movements',label:'Movimientos',icon:ArrowRightLeft},{id:'categories',label:'Categorías',icon:Target},{id:'export',label:'Exportar',icon:Download}];
  const WalletNav=({value,onChange})=><nav className="m2-wallet-nav">{walletTabs.map(item=><button className={value===item.id?'is-active':''} key={item.id} onClick={()=>onChange(item.id)}><item.icon/><span>{item.label}</span></button>)}</nav>;
  const WalletPage = ({ data, onUpdateFinance, quickAction }) => {
    const initial=routeParam('wallet','summary');const [section,setSection]=useState(initial);const [txType,setTxType]=useState('income');const finance=data.financeData||{};const rate=Number(finance.copRate||4000);const accounts=finance.accounts||[];const tx=finance.transactions||[];const inCop=value=>Number(value||0)*rate;const total=accounts.reduce((s,a)=>s+inCop(a.balance),0);const change=id=>{setSection(id);const u=new URL(location.href);u.searchParams.set('wallet',id);history.replaceState({},'',u)};
    const addTx=event=>{event.preventDefault();const fd=new FormData(event.currentTarget);const amount=Number(fd.get('amount')||0);if(!amount)return;onUpdateFinance(prev=>({...prev,transactions:[{id:uid('fin'),type:txType,amount:amount/rate,category:fd.get('category')||'food',accountId:fd.get('account')||prev.accounts?.[0]?.id,payee:fd.get('note')||'Movimiento',note:fd.get('note')||'',date:fd.get('date')||isoDate()},...(prev.transactions||[])]}));change('movements')};
    const exportData=()=>{const blob=new Blob([JSON.stringify(finance,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`habitflow-wallet-${isoDate()}.json`;a.click();URL.revokeObjectURL(url)};
    if(section==='add')return <div className="m2-page"><PageTitle title="Agregar" subtitle="" action={<button className="m2-back" onClick={()=>change('summary')}><ArrowLeft/></button>}/><Card className="m2-impact"><span>Moneda<strong>COP</strong></span><hr/><span>Impacto en tu wallet<small>Nuevo saldo estimado</small><b>{money(total,'COP')}</b></span></Card><form className="m2-wallet-form" onSubmit={addTx}><Tabs value={txType} onChange={setTxType} items={[{id:'income',label:'Ingreso',icon:ArrowUp},{id:'expense',label:'Gasto',icon:ArrowDown},{id:'transfer',label:'Transferencia',icon:ArrowRightLeft}]}/><label>Monto<div><b>$</b><input name="amount" type="number" placeholder="0,00"/><span>COP</span></div></label><label>Cuenta<select name="account">{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Categoría<select name="category">{(finance.categories||[]).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Fecha<input name="date" type="date" defaultValue={isoDate()}/></label><label>Nota (opcional)<input name="note" placeholder="Escribe una nota..."/></label><Button type="submit">Guardar movimiento</Button></form><WalletNav value="add" onChange={change}/></div>;
    if(section==='accounts')return <div className="m2-page"><PageTitle title="Cuentas" subtitle="" action={<Button onClick={()=>{const name=global.prompt('Nombre de la cuenta');if(name)onUpdateFinance(prev=>({...prev,accounts:[...(prev.accounts||[]),{id:uid('account'),name,type:'bank',currency:'COP',balance:0}]}))}}><Plus/>Nueva cuenta</Button>}/><Card className="m2-account-summary"><span>Saldo total en cuentas<strong>{money(total,'COP')}</strong><small>≈ {money(total/rate,'USD')}</small></span><hr/><span>Cuentas activas<strong>{accounts.length}</strong><small>de {accounts.length} cuentas</small></span></Card><h2 className="m2-section-title">Mis cuentas</h2><div className="m2-account-list">{accounts.map((a,index)=><Card key={a.id}><IconCircle tone={agendaTone(index)}><CreditCard/></IconCircle><span><strong>{a.name}</strong><small>{a.type||'Cuenta'}</small></span><b className={Number(a.balance)<0?'is-red':''}>{money(inCop(a.balance),'COP')}</b><em>COP</em><ChevronRight/></Card>)}</div><WalletNav value={section} onChange={change}/></div>;
    if(section==='movements')return <div className="m2-page"><PageTitle title="Movimientos" subtitle=""/><div className="m2-search"><Search/><input placeholder="Buscar movimientos..."/><button><ListFilter/></button></div><div className="m2-chip-row"><button className="is-active">Todos</button><button>Ingresos</button><button>Gastos</button><button>Transferencias</button></div><h2 className="m2-section-title">Recientes</h2><Card className="m2-movement-list">{tx.map((item,index)=><div key={item.id}><IconCircle tone={item.type==='income'?'green':item.type==='transfer'?'purple':'red'}>{item.type==='income'?<ArrowDown/>:item.type==='transfer'?<ArrowRightLeft/>:<CreditCard/>}</IconCircle><span><strong>{item.payee||item.note||'Movimiento'}</strong><small>{finance.categories?.find(c=>c.id===item.category)?.name||item.category}</small></span><time>{shortDate(item.date)}</time><b className={item.type==='income'?'is-green':item.type==='expense'?'is-red':''}>{item.type==='expense'?'-':'+'}{money(inCop(item.amount),'COP')}</b></div>)}</Card><WalletNav value={section} onChange={change}/></div>;
    if(section==='categories')return <div className="m2-page"><PageTitle title="Categorías" subtitle="" action={<button className="m2-back" onClick={()=>change('summary')}><ArrowLeft/></button>}/><Tabs value="expense" onChange={()=>{}} items={[{id:'expense',label:'Gastos'},{id:'income',label:'Ingresos'},{id:'transfer',label:'Transferencias'}]}/><h2 className="m2-section-title">Grupos de categorías</h2><div className="m2-category-list">{(finance.categories||[]).map((cat,index)=><Card key={cat.id}><IconCircle tone={agendaTone(index)}><Target/></IconCircle><i style={{background:cat.color}}/><strong>{cat.name}</strong><button>Editar</button><ChevronRight/></Card>)}</div><Button onClick={()=>{const name=global.prompt('Nombre de la categoría');if(name)onUpdateFinance(prev=>({...prev,categories:[...(prev.categories||[]),{id:uid('category'),name,color:'#f3132b'}]}))}}><Plus/>Nueva categoría</Button><WalletNav value={section} onChange={change}/></div>;
    if(section==='export')return <div className="m2-page"><PageTitle title="Exportar" subtitle="" action={<button className="m2-back" onClick={()=>change('summary')}><ArrowLeft/></button>}/><Card className="m2-export-intro"><IconCircle><FileText/></IconCircle><span><h2>Archivo personalizado</h2><p>Tu archivo se generará con los filtros y opciones seleccionadas.</p></span></Card><Card className="m2-export-card"><h2>Formato de exportación</h2><div className="m2-export-types"><button className="is-active"><FileText/>CSV</button><button><FileSpreadsheet/>Excel</button><button><FileText/>PDF</button></div><h2>Rango de fechas</h2><button className="m2-date-range"><CalendarDays/>1 may 2025 – 31 may 2025<ChevronDown/></button><h2>Incluir en el archivo</h2>{['Movimientos','Cuentas','Categorías','Próximos pagos'].map(item=><label key={item}><span>{item}</span><input type="checkbox" defaultChecked/></label>)}<Button onClick={exportData}><Download/>Exportar ahora</Button><small>Tu información está protegida y solo tú puedes verla.</small></Card><WalletNav value={section} onChange={change}/></div>;
    const income=tx.filter(i=>i.type==='income').reduce((s,i)=>s+inCop(i.amount),0);const expense=tx.filter(i=>i.type==='expense').reduce((s,i)=>s+inCop(i.amount),0);
    return <div className="m2-page"><PageTitle title="Wallet" subtitle=""/><div className="m2-currency"><button className="is-active">COP</button><button>USD</button><button>EUR</button></div><div className="m2-wallet-total"><span>Saldo total</span><strong>{money(total,'COP')}</strong><small>≈ {money(total/rate,'USD')}</small></div><div className="m2-wallet-actions">{[['add','Agregar',Plus],['accounts','Cuentas',CreditCard],['movements','Movimientos',ArrowRightLeft],['categories','Categorías',Target],['export','Exportar',Download]].map(([id,label,Icon])=><button key={id} onClick={()=>change(id)}><Icon/><span>{label}</span></button>)}</div><Card className="m2-wallet-chart"><header><h2>Resumen del período</h2><span>Este mes</span></header><div className="m2-area-chart">{[15,22,19,31,38,43,40,55,61,70,68,88].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div><footer><span>Ingresos<strong className="is-green">{money(income,'COP')}</strong></span><span>Gastos<strong className="is-red">{money(expense,'COP')}</strong></span><span>Neto<strong>{money(income-expense,'COP')}</strong></span></footer></Card><h2 className="m2-section-title">Movimientos recientes</h2><Card className="m2-movement-list">{tx.slice(0,4).map((item,index)=><div key={item.id}><IconCircle tone={item.type==='income'?'green':'red'}>{item.type==='income'?<ArrowDown/>:<CreditCard/>}</IconCircle><span><strong>{item.payee||item.note}</strong><small>{item.category}</small></span><time>{shortDate(item.date)}</time><b className={item.type==='income'?'is-green':'is-red'}>{item.type==='income'?'+':'-'}{money(inCop(item.amount),'COP')}</b></div>)}</Card><WalletNav value="summary" onChange={change}/></div>;
  };

  const HealthPage = ({ data, hydration, brushing, addHydration, addBrushing, onUpdateHealth }) => {
    const health=data.healthData||{};const meds=(health.medications||[]).filter(m=>m.isActive!==false);const next=meds.flatMap(m=>(m.times||[]).map(time=>({med:m,time}))).sort((a,b)=>a.time.localeCompare(b.time))[0];const waterPct=hydration.goal?Math.round(hydration.amount/hydration.goal*100):0;const brushPct=brushing.goal?Math.round(brushing.count/brushing.goal*100):0;
    const take=()=>{if(!next)return;onUpdateHealth(prev=>({...prev,takenLogs:[...(prev.takenLogs||[]),{id:uid('dose'),medicationId:next.med.id,date:isoDate(),scheduledTime:next.time,status:'taken'}]}))};
    return <div className="m2-page"><PageTitle title="Salud" subtitle="Tu cuidado, a la vista"/><div className="m2-health-grid"><Card className="m2-health-water"><header><h2><Droplet/>Hidratación</h2><span><Flame/> {hydration.streak||0} días</span></header><div className="m2-bottles">{Array.from({length:5},(_,i)=><i className={i<Math.round(waterPct/20)?'is-filled':''} key={i}/>)}</div><div><strong>{(hydration.amount/1000).toFixed(2)} L</strong><span>de {(hydration.goal/1000).toFixed(2)} L</span><em>{waterPct}%</em></div><ProgressRing value={waterPct} size={106}/><footer><Button secondary onClick={()=>addHydration(250)}>+250 ml</Button><Button secondary onClick={()=>addHydration(500)}>+500 ml</Button></footer></Card><Card className="m2-health-brush"><header><h2><Tooth/>Cepillado dental</h2><span><Flame/>{brushing.streak||0} días</span></header><strong>{brushing.count} <small>/ {brushing.goal} cepillados hoy</small></strong><div className="m2-progress"><i style={{width:`${brushPct}%`}}/></div><Button secondary onClick={addBrushing}>Registrar</Button><footer>¡Sigue así! {brushing.streak||0} días consecutivos</footer></Card><Card className="m2-health-sleep"><header><h2><Moon/>Sueño</h2><span><Flame/>0 días</span></header><strong>{health.sleep?.lastHours||'--'} <small>Dormido anoche</small></strong><hr/><span>Hora de dormir<b>{health.sleep?.bedtime||'--:--'}</b><small>Meta: 7–9 h</small></span><ProgressRing value={health.sleep?.percentage||0} size={96}/></Card><Card className="m2-health-weight"><header><h2><Activity/>Peso</h2><span>Actualizado hoy</span></header><strong>{health.weight?.current||'--'} kg</strong><small>{health.weight?.change||0} kg vs. hace 7 días</small><div className="m2-weight-chart">{[55,58,62,57,49,50,45].map((v,i)=><i key={i} style={{bottom:`${v}%`}}/>)}</div></Card><Card className="m2-health-med"><header><h2><Pill/>Medicación</h2><span><Flame/>{meds.length} activas</span></header><span>Próxima dosis<strong>{next?`${next.med.name} ${next.med.dose}`:'Sin dosis pendientes'}</strong><em>{next?`Hoy, ${next.time}`:''}</em></span><Button secondary onClick={take} disabled={!next}>Marcar como tomada</Button><footer><Bell/>Recordatorio activo · {next?.time||'--:--'}</footer></Card></div></div>;
  };

  const SettingsPage = ({ data }) => <div className="m2-page"><PageTitle title="Configuración" subtitle="Personaliza HabitFlow."/><Card className="m2-settings"><h2>Perfil</h2><p>{data.user?.name}</p><h2>Tema</h2><p>{data.user?.themeMode==='pinkLight'?'Claro Rosa':'Dark Puro'}</p><h2>Sincronización</h2><p>Tus cambios se guardan automáticamente.</p></Card></div>;

  const MobileTabletV2App = (props) => {
    const { data, view, navigate, moreOpen, setMoreOpen, creatorAccess, streak, dateLabel, onNotifications } = props;
    let page;
    if(view==='dashboard')page=<HomePage data={data} navigate={navigate} quickAction={props.onQuickAction} streak={streak}/>;
    else if(view==='habits')page=<HabitsPage data={data} onCompleteHabit={props.onCompleteHabit} hydration={props.hydration} onToggleHydrationWidget={props.onToggleHydrationWidget} quickAction={props.onQuickAction}/>;
    else if(view==='pomodoro')page=<PomodoroPage data={data} onUpdatePomodoro={props.onUpdatePomodoro}/>;
    else if(view==='agenda')page=<AgendaPage data={data} onUpdateAgenda={props.onUpdateAgenda}/>;
    else if(view==='workout')page=<WorkoutPage data={data} onUpdateWorkout={props.onUpdateWorkout}/>;
    else if(view==='dreams')page=<GoalsPage data={data} onUpdateDreamGoals={props.onUpdateDreamGoals}/>;
    else if(view==='finance')page=<WalletPage data={data} onUpdateFinance={props.onUpdateFinance} quickAction={props.onQuickAction}/>;
    else if(view==='health')page=<HealthPage data={data} hydration={props.hydration} brushing={props.brushing} addHydration={props.addHydration} addBrushing={props.addBrushing} onUpdateHealth={props.onUpdateHealth}/>;
    else page=<SettingsPage data={data}/>;
    return <div className={`mobile-v2 mobile-v2-${view}`} data-testid="mobile-tablet-v2-shell"><MobileV2Header userName={data.user?.name} dateLabel={dateLabel} streak={streak} onNotifications={onNotifications}/><main id="habitflow-main" tabIndex="-1">{page}</main>{view!=='finance'&&<MobileV2BottomNav view={view} onNavigate={navigate} moreOpen={moreOpen} onToggleMore={()=>setMoreOpen(!moreOpen)} workoutActive={view==='workout'}/>}<MobileV2MoreSheet open={moreOpen} view={view} onClose={()=>setMoreOpen(false)} onNavigate={navigate} creatorAccess={creatorAccess}/></div>;
  };

  global.HabitFlowMobileV2 = Object.freeze({ MobileTabletV2App, useMobileV2Viewport });
})(window);
