[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."habitflow-push-cron"]
  schedule = "* * * * *"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"
